app:
  realm: demo
  default-bank: TEST-01
  google: 784351879169-fbhd369t9dvnueu1nhm3lom2h6tlu2pu.apps.googleusercontent.com
spring:
  datasource:
    url: jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: false
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    username: poussy.magnette@gmail.com
    password: fwudamcgudlkenjz
    properties:
      mail:
        debug: true
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
logging:
  level:
    com.messio.demo: DEBUG
    org.springframework.security: INFO
  pattern:
    console: "%clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
